sudo: required

services:
  - docker

language: go

go:
  - 1.7.1

install:
  - go get -u github.com/golang/lint/golint

script:
  - export DOCKER_TAG=$TRAVIS_BRANCH
  - if [ "$TRAVIS_BRANCH" == "master" ]; then export DOCKER_TAG="latest"; fi
  - "echo DOCKER_TAG: $DOCKER_TAG"
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - make install && docker build -t "$TRAVIS_REPO_SLUG":"$DOCKER_TAG" . && echo Building "$TRAVIS_REPO_SLUG":"$DOCKER_TAG" && docker push "$TRAVIS_REPO_SLUG":"$DOCKER_TAG"
